apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tabby
  namespace: tabby
spec:
  serviceName: "tabby"
  replicas: 1
  selector:
    matchLabels:
      app: tabby
  template:
    metadata:
      labels:
        app: tabby
    spec:
      tolerations:
      - key: dedicated
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        dedicated: highPerf
      containers:
        - name: tabby
          image: tabbyml/tabby
          args:
            - serve
            - --model
            - StarCoder-1B
          command:
            - /opt/tabby/bin/tabby-cpu
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              #cpu: "4000m"
              #memory: "4Gi"
          volumeMounts:
            - mountPath: /data
              name: tabby-volume
  volumeClaimTemplates:
  - metadata:
      name: tabby-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi