apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  chart:
    spec:
      chart: ollama
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ollama
  values:
    ollama:
      models:
        #- saikatkumardey/tinyllama:latest
        - tinydolphin
