apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: showcases
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    # service:
    #   enabled: true
    #   type: LoadBalancer
    ingress:
      enabled: true
      className: ""
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: podinfo.home
      hosts:
        - host: podinfo.home
          paths:
            - path: /
              pathType: ImplementationSpecific        