apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: glock17
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: glock17
      interval: 1m
  values:
    replicaCount: 1